parameters:
#    myweb_admin.example.class: Myweb\AdminBundle\Example

services:
#    myweb_admin.example:
#        class: %myweb_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
