parameters:
#    myweb_data.example.class: Myweb\DataBundle\Example

services:
#    myweb_data.example:
#        class: %myweb_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
