parameters:
#    yameijq_grid.example.class: Yamei\Bundle\jqGridBundle\Example

services:
    test_service:
        class: Myweb\TestBundle\Controller\IndexController
        calls:
        - [setContainer, [@service_container]]
#        arguments: [@service_id, "plain_value", %parameter%]
